### PR TITLE
Save Disambiguation

### PR DESCRIPTION
**Pull request by evanwporter**
This was originally going to be a fix to #64. But then I realized that I was actually making a save error popup.

Next PR will be the fix to #64 though.

### CODE REVIEW

**Comment by evanwporter** [comment]
Note the unbound stuff was added using vscode to flesh it out. Its not production ready and the vite bundler will cut it out of the final product since its not used anywhere.

**Comment by andrewbenington** [comment]
This has been much needed, thank you. Is this ready for review? If so there's just a few styling things I want to tweak

**Comment by evanwporter** [comment]
@andrewbenington 

Yes its ready for review. Perhaps we should centralize the styling for each component in a css file.

**Comment by evanwporter** [comment]
@andrewbenington 

What's your thoughts on `css`? I heard (prob some reddit user lol) that css is bad for performance

**Comment by andrewbenington** [comment]
I mean we're kind of stuck with CSS, unless we want to have a 90s style website look 😆

CSS sucks but there isn't an alternative. The styles passed in as React props ultimately become CSS after React processes them. I would assume that styles declared in *.css files are more performant than styles passed in as props because you don't need any javascript. But i don't even know if that performance difference is noticeable.

Anyways, the way we declare styles probably doesn't matter performance-wise, but at some point I want to go through and standardize the styles bc they're kind of all over the place. I'm using emotion/joy for theming, which might add some overhead but it's worth it for an easy light/dark mode IMO

**Comment by andrewbenington** [comment]
I'd like to split this into separate PRs without the Unbound stuff. I know Vite won't include it in the build, but I'd rather not have the code on the main branch until it's functional

Also, if you take a look at the drag-and-drop PR, you'll see I added a general error pop up system that can be used for the save message here once that PR is merged

**Comment by andrewbenington** [comment]
@evanwporter So the "complementary plugin" strategy is kind of a shaky one, because you're trusting that every plugin knows about every other possibly conflicting plugin. I think this is a more elegant solution:

- replace `getSaveType()` with `getSaveTypes()`, which returns a list of all save types that identify the file as their own
- whenever there are more than one save type returned, use your `SelectPlugin` modal (renamed to `SelectSaveType` or something) to prompt the user for the appropriate type

I think this not only handles the conflicting plugin problem, but any possible conflicts with official save types as well. Plus, we don't have to worry about checking the save types in any particular order anymore

**Comment by evanwporter** [comment]
Looks good

**Comment by andrewbenington** [comment]
@evanwporter Let me know what you think. You can comment out these lines to force the modal to show up even if there's only one valid save type:

https://github.com/andrewbenington/OpenHome/blob/345b7889cd1dcc50004e346a660fdeada470c2e6/src/saves/SavesModal.tsx#L130-L133

**Review by andrewbenington — APPROVED** [review]

**Pull request merged**
