### PR TITLE
refactor: move from Electron to Tauri

### PR DESCRIPTION
**Pull request by andrewbenington**
**STILL IN PROGRESS, NOT ALL FUNCTIONALITY HAS BEEN RECREATED**

**Description**

Moving from Electron to Tauri to
- Reduce application size (#31 )
- Provide a snappier experience thanks to Tauri's native web renderer
- Allow for potential future Android and iOS versions

Other changes:
- Gen 5, LGPE, and PLA sprites have been removed for the time being to further reduce installer size
  - These sprites will be downloadable separately in the future
- A new drag-and-drop library has been introduced for a smoother, less buggy experience

### CODE REVIEW

**Comment by andrewbenington** [comment]
@evanwporter Here's my work so far. Some functions in the `TauriBackend` haven't been implemented yet, but it pretty much works as a read-only app.

I've only tested this on macOS so far so there might need to be some visual adjustments for other platforms.

**Comment by evanwporter** [comment]
@andrewbenington 

Looks good. I'll take a look at it later.

>Over 5000 files have been changed 😮

**Comment by andrewbenington** [comment]
The joy of having so many image files 😬

**Comment by evanwporter** [comment]
Windows looks good.

**Comment by andrewbenington** [comment]
It's not difficult, it's just time consuming because I'm testing each backend function individually to make sure peoples files don't get messed up. macOS looks good, but Linux has a couple visual issues I need to work out

**Comment by andrewbenington** [comment]
@evanwporter I think most of what's left is the transaction logic. I'm almost done with it, then I want to do a bunch of testing to make sure nothing is messed up.

Idk if you've looked at the transaction logic in the Electron app, but the way it works is that when a transaction is open, all file writes are instead written to that file name with `.tmp` at the end, and those temporary versions are only written over the original files when the whole transaction is committed. If the transaction is rolled back, all the temporary files are deleted.

This way we avoid writing some files and failing to write others, which could result in duped mons or deleted ones. This could happen if, for example, the user moves a save file's enclosing folder after that save file has been opened in the app.

**Comment by andrewbenington** [comment]
@evanwporter actually if you want to work on something, I think the last thing to implement in the backend aside from transactions is the suggested save finder. This might be a little complicated though because the save file validation will have to be done in the frontend unless we want to write new save file detection code in rust

**Comment by evanwporter** [comment]
@andrewbenington 

Still need to do `desamume` saves. Shouldn't be too hard. But lets see how this works.

**Comment by evanwporter** [comment]
@andrewbenington 

Do you use an auto formatter/linter. I noticed that you have often reformatted my code. I can run the formatter before I commit...

**Comment by andrewbenington** [comment]
@evanwporter yeah I use eslint and prettier, if you use VS code you can install those extensions and they should auto format when you save a file (based on the settings in .vscode)

**Comment by evanwporter** [comment]
@andrewbenington yeah I do use VScode so I downloaded both extensions. How are the tests?

**Comment by andrewbenington** [comment]
Did you write tests? or you mean manual testing?

I think it's about ready to merge. It seems to be working fine on mac. if it's working for you on windows i'm just going to try it out on linux one more time before i merge.

also, im going to do some git-fu to make sure it tracks all of the moved renderer files as the same. i will probably end up merging into a dev branch first after making an initial "move" commit on that branch

**Comment by evanwporter** [comment]
>Did you write tests? or you mean manual testing?

I meant the tests you mentioned you would run yesterday to see if everything works. Also vscode is warning me that `rollback_transaction` is not in use.

**Comment by evanwporter** [comment]
I'll let you know but everything work except the menu buttons.

@andrewbenington

**Comment by evanwporter** [comment]
image

Before merging this bar needs to be widened.

image

App state needs to removed.

image

~~This~~ Every sliding bar should be changed colors to fit the aesthetics.

**Comment by evanwporter** [comment]
image

These buttons are dead

**Comment by evanwporter** [comment]
Also

https://github.com/andrewbenington/OpenHome/blob/bd6a3c0f2f6461acb4c5fc0549fe8a64e243ab78/src/App.tsx#L99-L101

**Comment by andrewbenington** [comment]
@evanwporter I personally think that the white scroll bars fit the color scheme and are more visible than green ones, which blend into the background sometimes:
Screenshot 2024-12-06 at 6 37 34 PM
Also, the color you picked doesn't look great in dark mode. 
Screenshot 2024-12-06 at 6 37 44 PM

> These buttons are dead
Yeah they aren't supposed to be buttons, only the + sign is. Those should probably be tweaked to look less like buttons but that isn't part of this pull request

> App state needs to removed.
Yeah I'm pushing a change right now that only shows that in dev mode

**Comment by andrewbenington** [comment]
@evanwporter good catch with the rollback transaction thing, I'm not sure why the rust compiler didn't give me any warnings. do you have special rust lint rules enabled? if so what are they?

**Comment by andrewbenington** [comment]
Damn I made some merge mistakes

**Comment by evanwporter** [comment]
@andrewbenington 

I have the default settings enabled. `rust-analyzer` and the tauri compiler both catch this. But I think it might be easier for you to fix the `rust-analyzer`...

**Comment by evanwporter** [comment]
@andrewbenington 

What about this line? What does this refer too?

https://github.com/andrewbenington/OpenHome/blob/bd6a3c0f2f6461acb4c5fc0549fe8a64e243ab78/src/App.tsx#L99-L101

**Comment by andrewbenington** [comment]
Oh that file should be deleted I thought I deleted it. It was the tauri template app entry point

**Pull request merged**
