### PR TITLE
feat: add support for Pokémon Radical Red

### PR DESCRIPTION
**Pull request by andrewbenington**
**Description**

- Adds support for Pokémon Radical Red, thanks to the work of @evanwporter.
  - This code will eventually be moved to a plugin once the plugin system is finalized.
  - Fakemons and Sevii formes are not supported
  - Radical Red sprites are included for now until all sprites are moved to their own optional sprite packs
- Changes have been made to decentralize game-specific information. For example lookup maps for game names and species/forme support have been moved to functions in the SAV interface
  - This is necessary to prepare for the plugin system, where all code for save types will need to be self contained

### CODE REVIEW

**Review by evanwporter — DISMISSED** [review]
Looks really good

**Comment by andrewbenington** [comment]
@evanwporter what's the purpose of `isRR()`? it doesn't look like it's used anywhere. and what's the point of this function compared to `fileIsSave()`? the `fileIsSave()` function should be the one that returns whether the bytes are a valid Radical Red save

**Comment by evanwporter** [comment]
Yeah how does the 0xAC check work for G3 Saves? According to [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Save_data_structure_(Generation_III)) the game code appears at 0xAC in section 0. Section may not be at the beginning since the sections are shuffled. Now I believe RR has the same game code as FireRed. Now this creates issues when attempting to differentiate the two. Thus I added the `isRR` method to detect whether boxmons are stored using only 58 bytes (as opposed to the 80 as per usual in G3). This would help detect whether a Save is FR G3 or RR

**Comment by andrewbenington** [comment]
> Yeah how does the 0xAC check work for G3 Saves? According to [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Save_data_structure_(Generation_III)) the game code appears at 0xAC in section 0. Section may not be at the beginning since the sections are shuffled. Now I believe RR has the same game code as FireRed. Now this creates issues when attempting to differentiate the two. Thus I added the `isRR` method to detect whether boxmons are stored using only 58 bytes (as opposed to the 80 as per usual in G3). This would help detect whether a Save is FR G3 or RR

OpenHome unshuffles the sections when loading a gen 3 save, don't worry about that. but yes the 0xAC check is verifying the game code to make sure it's a valid gen 3 save file. But I see why this isn't actually very robust, as Emerald uses this location for the security key so it could really be any value.

Checking the size of pokémon in the box to differentiate Radical Red is a good idea. Let's move that code into the PK3RR file, and I will update the save detection function in G3SAV to check the original and verify the security key. My current idea is to try and decrypt the trainer and rival names with the security key, and make sure that field is the expected string format

**Comment by evanwporter** [comment]
> OpenHome unshuffles the sections when loading a gen 3 save

Yes. But afaik it doesn't unshuffle the section when checking for the game code. Instead it just looks at the bytes 0xAC bytes into the file which may or may not be the game code...

**Comment by andrewbenington** [comment]
> > OpenHome unshuffles the sections when loading a gen 3 save
> 
> Yes. But afaik it doesn't unshuffle the section when checking for the game code. Instead it just looks at the bytes 0xAC bytes into the file which may or may not be the game code...

Yes you're absolutely right, thank you for catching that. I just realized that myself. I'm updating the check now

**Comment by evanwporter** [comment]
The `findFirstSaveSection` in RR is how I did it for RR

**Comment by evanwporter** [comment]
```
// Similar process should be done for G3
// If this check and the G3 check both fail then
// that means that there are no native mons in the SAVE
// or that there are no mons in the first box. The result
// of both checks failing should be a prompt to specify
// which game the Save belongs too.
```

Here's the comment I wrote for `isRR`.

**Comment by andrewbenington** [comment]
I think I figured out a way to detect it using the security key. Emerald and FireRed/LeafGreen have two copies of the security key in the save data, and assuming Radical Red doesn't do the same thing we can just compare those locations and assume it's a vanilla save if they match. Let me make sure this works

**Comment by andrewbenington** [comment]
Ok so I think I've got a pretty foolproof detection method without having to check any pokemon in the boxes. basically:

- Emerald and FireRed have a security key used to decrypt parts of the save file
- Radical Red (at least in the save file you provided) seems to set this security key to 0
- Emerald/FireRed store a second copy of the security key

So my strategy is to assume it's Radical Red if the game code (value at `0xac`) is 1 and the security key is 0, and assume it's FireRed otherwise. If the game code is not 0 and the two security keys don't match, the file is not a valid gen 3 save file at all.

**Comment by evanwporter** [comment]
That's nice but now we have a whole new issue.

Something broke...

image

**Comment by andrewbenington** [comment]
that's not happening for me, is that when you try and view a mon in the save file?

**Comment by evanwporter** [comment]
Can you drop a screenshot? 

image

**Comment by andrewbenington** [comment]
Screenshot 2024-11-17 at 5 22 46 PM
Screenshot 2024-11-17 at 5 22 43 PM
Screenshot 2024-11-17 at 5 22 40 PM

**Comment by evanwporter** [comment]
Ah man I reverted the fork to a previous version where I know it works, and it has the same issues. I wonder whats up.

**Comment by evanwporter** [comment]
Also I don't think it correctly identifying RR saves

**Comment by andrewbenington** [comment]
Can we figure this out somewhere like Discord? It's hard to communicate through GitHub, especially in a pull request

**Comment by andrewbenington** [comment]
No problem. At least your issues are gone (for now lol)

Some things I want to address before this is merged:
- Moves are sometimes buggy when converting to PK3RR (one or more valid moves become "unknown move")
- Pokéball is missing for the Sableye in box 3 (should be a quick ball, but is 0. other mons in a quick ball seem fine?)
- I want to verify the transfer restrictions are accurate. For example, the sprites you uploaded don't include sprites for ursaluna blood moon or magearna original, but i want to try transferring those into Radical Red to see if they actually exist in game
  - Also, `Gen3RRPokemonIndex` has Magearna listed twice. I assume the second one should be Magearna-Original?

**Comment by evanwporter** [comment]
>I want to verify the transfer restrictions are accurate. For example, the sprites you uploaded don't include sprites for ursaluna blood moon or magearna original, but i want to try transferring those into Radical Red to see if they actually exist in game

image

This is the sprite from the pokedex online.

The spite doesn't exist but it does exist in game. I think your solution of replacing it with the OpenHome sprite is the best option here

Also Dialga-Origin and Palkia due indeed exist in game, they just aren't obtainable. But there is data defined for them so they can be cheated in I guess.

Second magearna is indeed the original one.

**Comment by evanwporter** [comment]
https://github.com/Skeli789/Dynamic-Pokemon-Expansion/tree/master/graphics/frontspr

Sprites are from here ^^

**Comment by andrewbenington** [comment]
I can confirm that as of now, transferring in Magearna-Original and Ursaluna-Bloodmoon don't work. I think it's something to do with the rr species lookup, because they disappear even if i transfer them in and reopen the save in OpenHome without ever opening it in Radical Red

**Comment by evanwporter** [comment]
Looks fantastic.

**Comment by evanwporter** [comment]
One last issue is with the OT game logo. It doesn't seem to be rendering or it could just be me...

**Comment by evanwporter** [comment]
Why did you change the met location byte from 0x34 to 0x33? This part wasn't reading correctly so I'm just curious how you found the correct offset.

**Comment by andrewbenington** [comment]
I think you were a byte off starting with substruct 3, I figured it out after looking through the C code. After fixing it im pretty sure the radical red game of origin is always 4, which is very nice. pushing more fixes now

**Comment by evanwporter** [comment]
>I think you were a byte off starting with substruct 3

Ah. That would make since. I thought there was some other logic to how it was stored, so I went hunting through the C code to see if I could find how it was stored, but the only thing of use is that I found how they were stored in RAM, which is not even that helpful. RIP.

>After fixing it im pretty sure the radical red game of origin is always 4, which is very nice. pushing more fixes now

That's really nice. 

Also I tried opening RR with unbound (another very popular Rom Hack) and it worksvery well. So adding support for unbound should be as easy as replacing the Species and Item lists with ones from Pokemon Unbound.

**Comment by andrewbenington** [comment]
That's great to hear about Unbound!

And yeah it's possible the layout in RAM is different thanks to how nested structs are memory-padded in C. It was honestly trial and error to figure out where the met level was located, but from there the layout is identical to the substructure3 struct.

**Review by andrewbenington — COMMENTED** [review]
`pluginOrigin` is also used in PK3RR, and should be present in all plugin PKM types. The difference is that `pluginOrigin` is only set to `radical_red` for pokemon that actually originated in Radical Red, while `pluginIdentifier` is `radical_red` for all PK3RR instances. `pluginIdentifier` should really be a static field, but static fields don't play nice with interfaces, and it's a pain to access static fields from an instance in JavaScript.

**Comment by evanwporter** [comment]
This is looking very polished. One last issue is that the `pluginOrigin` is not transferred across other instances of `PK#` (ie: converting a mon from OHPKM => PK7 => PK3RR loses the `pluginOrigin` of `radical_red`). This is a difficult issue to solve without subclassing every `PK#` or modifying `pokemon-file-js`. Let me know what you think.

@andrewbenington

**Comment by andrewbenington** [comment]
@evanwporter OpenHome always converts to OHPKM first when going between formats so that shouldn't be an issue. And that `OHPKM` data is loaded back from the local file whenever a tracked pokémon is found in a save. 

So the flow would be `PK3RR` -> `OHPKM` -> `PK7`, and then when the `OHPKM` is loaded again when you reopen the gen 7 save it will still have the `pluginOrigin` field that was stored locally.

I tested this myself, moving a Radical Red origin mon into Pokémon Blue and back, and it still said it was from Radical Red. Have you found an instance where this doesn't work?

**Comment by evanwporter** [comment]
@andrewbenington 

Also do you mind sharing the code you used to generate the `pokemon-files` using the schema jsons

**Comment by andrewbenington** [comment]
@evanwporter honestly I think it might be better to just show what will be shown in-game for a given format, so "obtained in a link trade", "in the Sinnoh region", etc depending on the source and destination. If someone wants to see the actual met location they can see that in an OHPKM or the mon's original format. Makes things simpler.

And yes I will move that generating code to the `pokemon-files` repo. It's written in Go and it's kinda messy, but it should at least work as a jumping off point for generating new formats

**Comment by andrewbenington** [comment]
@evanwporter ok the code generation stuff is up on `pokemon-files-js`. You'll need to install Go, but that's pretty straightforward

**Comment by evanwporter** [comment]
> I think it might be better to just show what will be shown in-game for a given format, so "obtained in a link trade", "in the Sinnoh region", etc depending on the source and destination. If someone wants to see the actual met location they can see that in an OHPKM or the mon's original format. Makes things simpler.

That is a really good point

**Comment by andrewbenington** [comment]
I think the Radical Red stuff is working well enough to merge now. I'm going to do one last review of the modified code. TBH I'm not super thrilled about adding so many PNG files to the codebase, but I'll make a seperate issue for moving sprites to their own downloadable resource packs to be taken care of later.

**Comment by evanwporter** [comment]
Not a great solution but we could combine the PNGs into a single sprite sheet then slice the sprite we need out of it. Would be a massive image.

**Comment by andrewbenington** [comment]
> Not a great solution but we could combine the PNGs into a single sprite sheet then slice the sprite we need out of it. Would be a massive image.

That wouldn't reduce the size much, and any time we display a sprite the entire dex's sprites would need to be loaded into memory, which would take a long time and chew up resources. This is fine for now.

**Pull request merged**
