### PR TITLE
fix: recent saves page

### LINKED ISSUE #87: bug: broken open button + last modified data in recent saves (grid view)
In the recent saves grid view, the open button is disabled and "last modified" data is not present.

### PR DESCRIPTION
**Pull request by andrewbenington**
**Description**

- Recent save validation happens on the rust side
  - `valid` is set to `false` if the file is missing or inaccessible
  - `modifiedDate` is once again included in the save data
- Open button works again in grid view mode
- Grid view has a details menu, replacing delete button
- Save card menu button visual updates

**Issue**

Fixes #87

### CODE REVIEW

**Comment by evanwporter** [comment]
This fix introduces the following error:

image

Everything before this commit is fine.

**Comment by andrewbenington** [comment]
@evanwporter can you attach your `recent_saves.json`? This must be because an old version of the app stored the `game` value as a string and you haven't opened that save since that version. I'll work on a hotfix

**Comment by andrewbenington** [comment]
@evanwporter actually can you just clone the [legacy-recent-saves-fix](https://github.com/andrewbenington/OpenHome/tree/legacy-recent-saves-fix) branch and see if that fixes it for you?

**Comment by evanwporter** [comment]
@andrewbenington 

[recent_saves.json](https://github.com/user-attachments/files/18220979/recent_saves.json)

**Comment by evanwporter** [comment]
@andrewbenington 

```
{
  "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\0011c500\\data\\00000001\\main": {
    "filePath": {
      "base": "main",
      "dir": "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\0011c500\\data\\00000001",
      "ext": "",
      "name": "main",
      "raw": "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\0011c500\\data\\00000001\\main",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 26,
    "lastModified": 1730996697668.412,
    "lastOpened": 1731100535450,
    "saveType": 16,
    "trainerID": "19158",
    "trainerName": "Ruby",
    "valid": true
  },
  "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\001b5000\\data\\00000001\\main": {
    "filePath": {
      "base": "main",
      "dir": "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\001b5000\\data\\00000001",
      "ext": "",
      "name": "main",
      "raw": "REDACTED\\AppData\\Roaming\\Citra\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\001b5000\\data\\00000001\\main",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 32,
    "lastModified": 1731121321159.0215,
    "lastOpened": 1731177901356,
    "saveType": 16,
    "trainerID": "614851",
    "trainerName": "Photon",
    "valid": true
  },
  "REDACTED\\Downloads\\80% unbound.sav": {
    "filePath": {
      "dir": "REDACTED\\Downloads",
      "ext": "",
      "name": "80% unbound.sav",
      "raw": "REDACTED\\Downloads\\80% unbound.sav",
      "separator": "\\"
    },
    "game": 4,
    "lastOpened": 1734837676987,
    "pluginIdentifier": "unbound",
    "trainerID": "39288",
    "trainerName": "Ksh"
  },
  "REDACTED\\Roms\\Blaze Black 2\\Blaze Black 2.sav": {
    "filePath": {
      "base": "Blaze Black 2.sav",
      "dir": "REDACTED\\Roms\\Blaze Black 2",
      "ext": ".sav",
      "name": "Blaze Black 2",
      "raw": "REDACTED\\Roms\\Blaze Black 2\\Blaze Black 2.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 23,
    "lastModified": 1730244732475.4824,
    "lastOpened": 1730244706562,
    "saveType": 14,
    "trainerID": "28126",
    "trainerName": "Black",
    "valid": true
  },
  "REDACTED\\Roms\\Emerald\\Emerald.sav": {
    "filePath": {
      "base": "Emerald.sav",
      "dir": "REDACTED\\Roms\\Emerald",
      "ext": ".sav",
      "name": "Emerald",
      "raw": "REDACTED\\Roms\\Emerald\\Emerald.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 3,
    "lastModified": 1731286603965,
    "lastOpened": 1731365184031,
    "saveType": 10,
    "trainerID": "17925",
    "trainerName": "Emerald",
    "valid": true
  },
  "REDACTED\\Roms\\Emerald\\Inclement Emerald - Copy.sav": {
    "filePath": {
      "base": "Inclement Emerald - Copy.sav",
      "dir": "REDACTED\\Roms\\Emerald",
      "ext": ".sav",
      "name": "Inclement Emerald - Copy",
      "raw": "REDACTED\\Roms\\Emerald\\Inclement Emerald - Copy.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": "3",
    "lastOpened": 1733463766961,
    "saveType": 8,
    "trainerID": "08128",
    "trainerName": "Ink",
    "valid": true
  },
  "REDACTED\\Roms\\Fire Red\\rrSpreadOutBoxes.sav": {
    "filePath": {
      "base": "rrSpreadOutBoxes.sav",
      "dir": "REDACTED\\Roms\\Fire Red",
      "ext": ".sav",
      "name": "rrSpreadOutBoxes",
      "raw": "REDACTED\\Roms\\Fire Red\\rrSpreadOutBoxes.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 4,
    "lastOpened": 1734837447136,
    "pluginIdentifier": "radical_red",
    "trainerID": "10334",
    "trainerName": "Radical"
  },
  "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum (Titan).dsv": {
    "filePath": {
      "base": "Renegade Platinum (Titan).dsv",
      "dir": "REDACTED\\Roms\\Renegade Platinum",
      "ext": ".dsv",
      "name": "Renegade Platinum (Titan)",
      "raw": "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum (Titan).dsv",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 12,
    "lastOpened": 1734386688818,
    "trainerID": "23161",
    "trainerName": "Titan"
  },
  "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum - Copy.sav": {
    "filePath": {
      "base": "Renegade Platinum - Copy.sav",
      "dir": "REDACTED\\Roms\\Renegade Platinum",
      "ext": ".sav",
      "name": "Renegade Platinum - Copy",
      "raw": "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum - Copy.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 12,
    "lastModified": 1730244577466.7898,
    "lastOpened": 1730244373725,
    "saveType": 12,
    "trainerID": "44128",
    "trainerName": "Dusk",
    "valid": true
  },
  "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum.sav.2": {
    "filePath": {
      "base": "Renegade Platinum.sav.2",
      "dir": "REDACTED\\Roms\\Renegade Platinum",
      "ext": ".2",
      "name": "Renegade Platinum.sav",
      "raw": "REDACTED\\Roms\\Renegade Platinum\\Renegade Platinum.sav.2",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 12,
    "lastModified": 1730244577467.3196,
    "lastOpened": 1730244384136,
    "saveType": 12,
    "trainerID": "39275",
    "trainerName": "Diamond",
    "valid": true
  },
  "REDACTED\\Roms\\Sacred Gold\\Sacred Gold.sav": {
    "filePath": {
      "base": "Sacred Gold.sav",
      "dir": "REDACTED\\Roms\\Sacred Gold",
      "ext": ".sav",
      "name": "Sacred Gold",
      "raw": "REDACTED\\Roms\\Sacred Gold\\Sacred Gold.sav",
      "root": "C:\\",
      "separator": "\\"
    },
    "game": 7,
    "lastModified": 1730244577458.4312,
    "lastOpened": 1730243850248,
    "saveType": 13,
    "trainerID": "27772",
    "trainerName": "Gold",
    "valid": true
  }
}
```

**Comment by evanwporter** [comment]
> @evanwporter actually can you just clone the [legacy-recent-saves-fix](https://github.com/andrewbenington/OpenHome/tree/legacy-recent-saves-fix) branch and see if that fixes it for you?

@andrewbenington this works.

**Pull request merged**
