### PR TITLE
Download Sprites as Resource Packs

### PR DESCRIPTION
**Pull request by evanwporter**
```
use std::fs;
use reqwest::blocking::Client;
use reqwest::Url;
use std::io::Write;

fn download_images_from_github_folder(
    folder_url: &str,
    save_dir: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::new();

    let response = client
        .get(folder_url)
        .header("User-Agent", "OpenHome")
        .send()?
        .text()?;

    let files: serde_json::Value = serde_json::from_str(&response)?;
    let file_urls: Vec<&str> = files
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|file| {
            if let Some(file_name) = file.get("name") {
                // Filter for .png files
                if file_name.as_str()?.ends_with(".png") {
                    return file.get("download_url")?.as_str();
                }
            }
            None
        })
        .collect();

    fs::create_dir_all(save_dir)?;

    for url in file_urls {
        let parsed_url = Url::parse(url)?;
        let image_name = parsed_url
            .path_segments()
            .and_then(|segments| segments.last())
            .unwrap();

        let response = client.get(url).send()?;
        let mut file = fs::File::create(format!("{}/{}", save_dir, image_name))?;
        file.write_all(&response.bytes()?)?;
        println!("Downloaded: {}", image_name);
    }

    println!("All images downloaded successfully!");
    Ok(())
}

fn main() {
    let github_folder_url = "https://api.github.com/repos/andrewbenington/OpenHome/contents/public/sprites/gen1";
    let save_dir = "./test_sprites";

    match download_images_from_github_folder(github_folder_url, save_dir) {
        Ok(_) => println!("Test successful! Images downloaded to: {}", save_dir),
        Err(e) => eprintln!("Test failed: {}", e),
    }
}
```

The only thing I've tested is `util::download_images_from_github_folder` using the above code.

@andrewbenington

### CODE REVIEW

**Comment by evanwporter** [comment]
May want to think about using `ureq` instead of `reqwest`

**Comment by evanwporter** [comment]
@andrewbenington 

W/ the most recent commit it works. The aesthetics and the number buttons need to the tweaked, but for now it works pretty well.

**Comment by evanwporter** [comment]
Also it prints a lot of stuff to console in Rust. This is for debugging purposes but it should be removed

**Comment by andrewbenington** [comment]
Awesome, thanks for starting on this. We should probably make the resource packs zip files though, to speed up downloads

**Comment by andrewbenington** [comment]
Also let's make this a draft for now, there's a lot of work to do. This is a good start though. I'm going to make a separate page to browse and download asset packs.

**Comment by evanwporter** [comment]
>Also let's make this a draft for now, there's a lot of work to do.

Yep, that's what I meant to do.

**Comment by evanwporter** [comment]
>Awesome, thanks for starting on this. We should probably make the resource packs zip files though, to speed up downloads

Between downloading bare files and unzipping I think it should be the same speed, depends on whether github rate limits the user though.

**Comment by evanwporter** [comment]
Now there are two function `download_images_from_github_folder` and `download_and_unpack_zip`, we should figure out which one will be faster. Github will prefer us using a zip though lol

@andrewbenington

**Comment by evanwporter** [comment]
What needs to be done is:

* Store which zips are downloaded in settings or a global function that check this by checking whether a sprite folder exists. 
  * If we go the settings route then at load the sprites will need to be downloaded if they aren't already. Otherwise the settings will need to change itself.
* Modify how it looks (ie: don't display download & delete--one or the other).
* Adjust the `getSprite` so it uses the sprite path.

**Comment by andrewbenington** [comment]
I'm going to tinker around with this and get back to you. I think the best design is to let the plugin determine the sprite to return instead of relying on hard coded folders

**Comment by evanwporter** [comment]
@andrewbenington 

Yeah that sounds good. Currently the rust code (and I recommend keeping it in rust for that boost) saves the sprites to `/storage/sprites/gen1`. Well `gen1` can be changed so idk if this is different from what you are thinking?

**Comment by evanwporter** [comment]
@andrewbenington 

Also can you merge the `legacy-recent-saves-fix` branch and look at the unbound PR. The unbound PR is ready to be merged into main. I included in it fixes for #91

**Comment by andrewbenington** [comment]
Right, but I'm not sure how you would update `getSprite` to find those sprites without hardcoding the path?

**Comment by evanwporter** [comment]
> Right, but I'm not sure how you would update `getSprite` to find those sprites without hardcoding the path?

The sprites are saved to the same place as `settings.json`.

@andrewbenington

**Comment by andrewbenington** [comment]
> > Right, but I'm not sure how you would update `getSprite` to find those sprites without hardcoding the path?
> 
> The sprites are saved to the same place as `settings.json`.
> 
> @andrewbenington

What I mean is this:
Let's say that after this resource pack code is merged into main and a new release is published, I want to publish a new resource pack containing Gen 5 sprites. How would that work? With your strategy, the application would already have to know to check a folder like `storage/sprites/gen5`. With my strategy, the plugin could be downloaded and have its `getMonSpritePath` function called, without having to push out an update for the app itself.
This also lets other people make their own resource packs without needing to touch the OpenHome codebase

**Comment by andrewbenington** [comment]
this should be closed in favor of #95, which includes all of the functionality here plus future-proofing for other types of plugins

**Pull request closed without merging**
