### PR TITLE
feat: in app item storage bag

### PR DESCRIPTION
**Pull request by evanwporter**
**Description**

This creates a bag within OpenHome that allows the transfer of items. The purpose of this other than replicating an actual in game bag, is to allow items to be kept instead of lost when a mon is sent to a game with an item that doesn't exist in the said game. Currently the bag is implemented and items can be given to mons as well as dropped in the bag. But the bag is not saved when OH is closed.

*NOT URGENT*

**Issue**

Elegant solution to Issue #55.

### CODE REVIEW

**Comment by andrewbenington** [comment]
This is going to be a bit messy thanks to the moved files for tauri, but at least now the files are tracked as the same. I'm going to resolve the merge conflicts later today when I have time

**Comment by evanwporter** [comment]
The bag-box is almost done but I think it should still be included merged within separate releases. The next release should OpenHome v1.0.0 and should just include Tauri. v1.1.0 can be the bag-box @andrewbenington

**Comment by andrewbenington** [comment]
This branch might need to be manually recreated, sorry. I pruned all of the git history for image files which results in rewriting all past commits. Now the git metadata size is no longer ~1GB, at least, so cloning shouldn't take so long anymore

**Comment by evanwporter** [comment]
@andrewbenington 

yeah this was out of date with the tauri stuff already. I merged some of it over to `bagbox` but then realized it would be more difficult to port since there's the new dragging lib.

**Pull request closed without merging**
