### PR TITLE
Fixed issue with data-race.

### PR DESCRIPTION
**Pull request by evanwporter**
Each time you open recent saves it presents the saves in a random order.

### CODE REVIEW

**Comment by evanwporter** [comment]
This is due to it asynchronously grabbing the saves, so some data may arrive first. The solution is to sort them.

**Comment by andrewbenington** [comment]
this is actually just #96, it's trying to sort by last modified but that field is broken. should be fixed by addressing #96

**Comment by evanwporter** [comment]
@andrewbenington 

Last modified works. Last opened does not.

**Comment by andrewbenington** [comment]
> @andrewbenington 
> 
> 
> 
> Last modified works. Last opened does not.

my bad, that's what i meant. the save cards are sorted by last opened already

**Comment by evanwporter** [comment]
@andrewbenington 

So is the solution to change the sorting method until `lastOpened` is implemented. But honestly I think `lastModified` is the best way to sort it

**Comment by andrewbenington** [comment]
https://github.com/andrewbenington/OpenHome/blob/1238696ff66a6fffcb191e5f6bc59f0d81e200b7/src/saves/RecentSaves.tsx#L208
https://github.com/andrewbenington/OpenHome/blob/394849b74d141e478a681099eb6fb256d417df1a/src/saves/RecentSaves.tsx#L214-L226

Adding a sort to where you put it will not affect either display mode when `lastOpened` is fixed, because both display modes already sort by that field. Closing this because the issue will be fixed when #96 is addressed

**Comment by andrewbenington** [comment]
> @andrewbenington
> 
> So is the solution to change the sorting method until `lastOpened` is implemented. But honestly I think `lastModified` is the best way to sort it

I disagree with this. `lastModified` is not when the file was last modified by OpenHome, but when the file itself was last modified by the operating system. Recent Saves should work like any other editing app with a "last opened" file selector.

**Comment by evanwporter** [comment]
okay

**Pull request closed without merging**
