### PR TITLE
fix: save card size to settings

### PR DESCRIPTION
**Pull request by evanwporter**
Holds state throughout program running.

This implementation seems somewhat laggy due to the constant re-rendering also having to update state. So we may want to changing state until the mouse click is released, or even better until the save window is closed. Something to think about anyways.

 I was using the `save-not-found-error` branch so that we don't have to deal with merge conflicts. <sub><sup>also I forgot to switch</sup></sub>

### CODE REVIEW

**Comment by andrewbenington** [comment]
I think the lagging could be fixed if it was changed from a continuous slider to one with distinct values, like intervals of 20px. That way it only rerenders 1/20 of the number of times it would compared to a continuous 1px interval slider

**Comment by andrewbenington** [comment]
@evanwporter 
I did a couple things:
- The function that updates the settings file is now debounced at 500ms, meaning it will wait until the settings have not been updated for at least 500ms before actually updating the settings file
- Set the slider step to 50
- Ran the linter/formatter on your changed files

Also, could you run the linting command (`npm run lint`) before you push? On main, I added a workflow to enforce linting and style, which means the PR will fail if the linter fails. If you're using VS code, I use the `esbenp.prettier-vscode` extension which also lets you see linting errors in real time, and will auto-format on file save if you have that enabled

**Comment by evanwporter** [comment]
@andrewbenington 

I installed prettier. Its really good, it reminds of C# dev. Is this in addition to running npm run lint

**Comment by andrewbenington** [comment]
i added an eslint plugin for prettier, so running eslint (including through `npm run lint` should do all the prettier formatting itself.

and yes idk how i ever survived without prettier, it's so nice to see everything snap into place

**Review by andrewbenington — APPROVED** [review]

**Pull request merged**
