### PR TITLE
Added a basic RadicalRed typescript sav reader

### PR DESCRIPTION
**Pull request by evanwporter**
Adds a method for decrypting Radical Red saves.  See #41. It parses it correctly, however there are some issues with exporting it to a sav. In particular it seems the OHPKM class is not fully compatible with PK3RR, so some work will definitely need to be done here to ensure full compatibility. As an alternative a hacky method is just to convert PK3RR files to Gen 7, 8, 9. Whichever is the latest gen that Pokémon appears in.

But until the PK3RR commit is integrated into the pokemon-species module, its best to keep this on the backburner since accepting this commit will only cause errors.

### CODE REVIEW

**Comment by evanwporter** [comment]
Probably best to merge this with another branch. Again this isn't completely finished, but its close!!! Things todo are:

* Create Items db for RR ([Items.txt](https://github.com/user-attachments/files/17604886/Items.txt))
* Create Moves db for RR ([Moves.txt](https://github.com/user-attachments/files/17604887/Moves.txt))
* Create Species/DEX db for RR ([Species.txt](https://github.com/user-attachments/files/17604889/Species.txt))
* Parse moves index within PK3RR
* Expand OHPKM to allow interconversion

**Comment by andrewbenington** [comment]
I'm going to make a branch for this, we don't want `main` to break.

I really love the idea of ROM hack support; my pie-in-the-sky goal is to make ROM hack saves supported via a plugin system, but in the meantime let's just keep the RR save type in its own separate folder (`SAVTYPES/ROM`?).

By the way, if you want to use a local version of the `pokemon-files-js` library for development, you can change the version of "pokemon-files" in `package.json` to a path to the location on your machine. I do it like this:
```json
...
"dependencies": {
    ...
    "pokemon-files": "../pokemon-files",
```

**Comment by evanwporter** [comment]
I think most ROM hacks simply expand the pokedex, the number of available items, and the number of moves. They don't modify how the saves work. Radical Red and Unbound are the only ones that do this afaik. So a plugin system could be as simple a list of species and items into a folder for the program to read.

**Comment by evanwporter** [comment]
> By the way, if you want to use a local version of the `pokemon-files-js` library for development, you can change the version of "pokemon-files" in `package.json` to a path to the location on your machine. I do it like this:
> 
> ```json
> ...
> "dependencies": {
>     ...
>     "pokemon-files": "../pokemon-files",
> ```

This is really helpful.

**Pull request closed without merging**
